version: '3.8'
services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  product-service:
    build: ./product-service
    ports:
      - "8001:8000"
    environment:
      - DEBUG=1

  cart-service:
    build: ./cart-service
    ports:
      - "8002:8000"
    environment:
      - DEBUG=1

  order-service:
    build: ./order-service
    ports:
      - "8003:8000"
    environment:
      - DEBUG=1

  payment-service:
    build: ./payment-service
    ports:
      - "8004:8000"
    environment:
      - DEBUG=1

  notification-service:
    build: ./notification-service
    ports:
      - "8005:8000"
    environment:
      - DEBUG=1

  api-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
